### ISSUE TITLE
Home Screen Layout

### ISSUE THREAD

**Issue by mewil** [mewil/woozy#2]

**Comment by meekray** [comment]
https://www.figma.com/file/HlOYfwMJ31E2sH7UC8erMz/Figma?node-id=0%3A1

**Comment by mewil** [comment]
This is the current home page code, it's a react component with some other things going on. I would focus on using styled-components (see the Container object) to create components in the render method of the class.

https://github.com/mewil/woozy/blob/master/app/home/components/home-page.js

**Comment by meekray** [comment]
Initial layout is done.
