### ISSUE TITLE
Woozy Setup Screens (3 or 4)

### ISSUE THREAD

**Issue by meekray** [mewil/woozy#7]
https://docs.google.com/presentation/d/1IdVy7mCArIY08o2Wc1vdvWkN417XL5KjvDedKQFsDSo/edit#slide=id.g82da9ebe9d_0_100

Basically, the Choose Your Friends shapes

**Comment by mewil** [comment]
Adding a file in [this directory](https://github.com/mewil/woozy/tree/master/app/settings/components) with a React component [such as this](https://github.com/mewil/woozy/blob/master/app/home/components/home-page.js) would be a good start. See [my comment](https://github.com/mewil/woozy/issues/3#issuecomment-609476525) on #3 for how to set up a new route for a settings page. Before we make it a modal it may be easier to work on it in a separate page, using a new key in the [ROUTES object](https://github.com/mewil/woozy/blob/master/app/app/constants.js) such as `SETTINGS: 'settings',`. Also make sure to check with @aditikr123 so you guys don't overlap work, I'm posting this same comment on #6
